### ISSUE TITLE
Need to merge GtkWidget->EventBox subclassing support from gtk3

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk4#2]
See summary :)

**Comment by sdroege** [comment]
https://github.com/gtk-rs/gtk/pull/861
https://github.com/gtk-rs/gtk/pull/863
https://github.com/gtk-rs/gtk/pull/864
https://github.com/gtk-rs/gtk/pull/865
https://github.com/gtk-rs/gtk/pull/868
https://github.com/gtk-rs/gtk/pull/869
https://github.com/gtk-rs/gtk/pull/871
https://github.com/gtk-rs/gtk/pull/873

**Comment by sfanxiang** [comment]
Note: `EventBox` doesn't actually exist in gtk4. But the rest of them are generally valid.
